openapi: 3.0.3
info:
  title: Teacher - Nodejs REST API Service
  description: >-
    This is a sample API specification
  version: 1.0.0
servers:
  - url: https://50bd1911-1fb1-4680-88bb-05745d943012-dev.e1-eu-north-azure.choreoapis.dev/soa-project/teacherservice/v1.0/teacher-service
paths:
  /fetch-all:
    summary: List all teachers
    get:
      summary: List all teachers
      operationId: ListAllTeachers
      tags:
        - teachers
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeyValue"
  
  /test:
    summary: Test
    get:
      summary: Test
      operationId: Test
      tags:
        - test
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Key"

components:
  schemas:
    Key:
      type: object
      properties:
        uuid:
          type: string
          example: "my-uuid"
    Status:
      type: object
      properties:
        status:
          type: string
          example: "read"
    KeyValue:
      type: object
      required:
        - id
        - firstName
        - lastName
        - gender
        - birthday
        - grade
        - diplome
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          example: "1"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        gender:
          type: string
          example: "M"
        birthday:
          type: string
          example: "20-08-2001"
        grade:
          type: string
          example: "Doctor"
        diplome:
          type: string
          example: "Doctor"
        createdAt:
          type: string
          example: "20-08-2018"
        updatedAt:
          type: string
          example: "20-08-2018"
        
    StringArray:
      type: array
      items:
        type: string